# params used for both training and testing
net: vgg16
dataset_dir: data
img_width: 224
img_height: 224

# params used only for training
batch_size: 32
epochs: 50
train_set_size: 22000
val_set_size: 3000
model_to_save_name: vgg16_model.h5

# params used only for testing
model_to_load_name: best_vgg16_model.ep-46_acc-0.95.h5
save_predictions: True
predictions_file_name: vgg16_predictions.csv
