net: vgg16
dataset_dir: data
batch_size: 32
img_width: 224
img_height: 224
epochs: 50
train_set_size: 22000
val_set_size: 3000
model_to_save_name: vgg16_model.h5
model_to_load_name: best_vgg16_model.ep-46_acc-0.95.h5
save_predictions: True
predictions_file_name: vgg16_predictions.csv
